### ISSUE TITLE
Fix Intermittently Failing Unit Test

### ISSUE THREAD

**Issue by aphralG** [nginx/agent#259] opened 2023-03-16 12:34 UTC
The unit test on the pipeline fails intermittently with the error below. It seems to be the `commander_test.go` that is failing. 

Example of pipeline failing: https://github.com/nginx/agent/actions/runs/4436873229/jobs/7785851614

Error:
```Send Command: meta:<message_id:"1234" > 
time="2023-03-16T12:12:39Z" level=info msg="Commander received meta:<message_id:\"1234\" > , <nil>"
Recv Command: <nil>
Recv Command Error: rpc error: code = Canceled desc = context canceled
time="2023-03-16T12:12:39Z" level=info msg="Commander received <nil>, rpc error: code = Canceled desc = grpc: the client connection is closing"
time="2023-03-16T12:12:39Z" level=error msg="Commander Channel Recv: error communicating with bufnet, code=Canceled, message=grpc: the client connection is closing"
time="2023-03-16T12:12:39Z" level=info msg="Commander Channel Recv: retrying to connect to bufnet"
time="2023-03-16T12:12:39Z" level=warning msg="Error closing old grpc connection: rpc error: code = Canceled desc = grpc: the client connection is closing"
time="2023-03-16T12:12:39Z" level=error msg="Unable to create command channel: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing closed\""
time="2023-03-16T12:12:39Z" level=info msg="Commander retrying to connect to bufnet"
Recv Command: meta:<message_id:"1234" > 
Recv Command: <nil>
Recv Command Error: rpc error: code = Canceled desc = context canceled```

**Comment by redaHamioui** [comment] 2023-04-02 20:11
how can i reproduce the bug ?

**Comment by oliveromahony** [comment] 2023-04-03 12:32
Thanks, I think running the tests in the pipeline saw inconsistent behavior and the intermittent failures. Running the test locally might reproduce the issue. I added this fix https://github.com/nginx/agent/pull/271 to tackle the problem. I'll update this if anything else needs to be done, otherwise I'll close it in a week or so

**Comment by Dean-Coakley** [comment] 2023-04-06 13:46
Please keep open. Still seeing intermittent failures: https://github.com/nginx/agent/actions/runs/4629318982/jobs/8189426092

**Comment by oliveromahony** [comment] 2023-04-11 11:03
@redaHamioui we still have this issue if you want to take a look? Some changes were made in https://github.com/nginx/agent/pull/268 to address it but I can get it to fail locally running the following command ```go test -timeout 30s github.com/nginx/agent/sdk/v2/client -v -count=10```

It looks like a race condition with the channels is causing the problem

**Comment by oliveromahony** [comment] 2023-09-07 10:32
this appears to be resolved

**Closed by oliveromahony** 2023-09-07 10:32 UTC
Labels: bug, good-first-issue
